export const PLANS = [
    {
        name:"Free",
        slug:"free",
        quota:10,
        pagesPerPDF:5,
        price:{
            amount:0,
            priceIds:{
                test:'',
                production:'',
            },
        },
    },
    {
        name:"Pro",
        slug:"pro",
        quota:50,
        pagesPerPDF:25,
        price:{
            amount:4.99,
            priceIds:{
                test:'price_1ODQRnIovLAVQFeKpLK6Yu0g',
                production:'',
            },
        },
    },
]